# Generated by Django 6.1 on 2026-10-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('maggi_taco', 'Maggi & Taco'), ('byob', 'BYOB Section')], max_length=30)),
                ('brand', models.CharField(blank=True, help_text='e.g. balaji, lays, kurkure, bingo, doritos, nachos, taco, maggie', max_length=50)),
                ('price_single', models.IntegerField(blank=True, help_text='Price when item has single fixed price', null=True)),
                ('price_small', models.IntegerField(blank=True, help_text='Small size price for BYOB', null=True)),
                ('price_large', models.IntegerField(blank=True, help_text='Large size price for BYOB', null=True)),
                ('description', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('has_wafer_options', models.BooleanField(default=False, help_text='True for Maggie Crunch Box')),
                ('is_available', models.BooleanField(default=True)),
                ('order_rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order_rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, default='Guest', max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('payment_mode', models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash')], default='upi', max_length=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('preparing', 'Preparing'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('subtotal', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, default='Regular', max_length=20)),
                ('unit_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('selected_wafers', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stall.order')),
            ],
        ),
    ]
